CREATE TABLE IF NOT EXISTS `users` (
	`id` INT(255) NOT NULL AUTO_INCREMENT,
	`username` VARCHAR(255) NULL DEFAULT NULL,
	`beam` VARCHAR(255) NULL DEFAULT '',
	`twitch` VARCHAR(255) NULL DEFAULT '',
	`twitter` VARCHAR(255) NULL DEFAULT '',
	`email` VARCHAR(255) NULL DEFAULT NULL,
	PRIMARY KEY (`id`),
	UNIQUE INDEX `username` (`username`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
AUTO_INCREMENT=3
;
